"""
figstyle.py — shared look for every generated "research interest" figure.

Import it, call setup(), draw, then save(fig, path).  Every figure on the
homepage must come out of this module so the 15 pictures read as one set.
save() also stamps "Generated by AI" bottom-right inside the image; this is
a rule for every generated image in the Homepage folder (see Homepage/CLAUDE.md).

    import sys; sys.path.insert(0, "<scratchpad>")
    import figstyle as fs
    fs.setup()
    fig, ax = fs.figure()            # 4:3, 1200 x 900 px when saved
    ...
    fs.save(fig, "<scratchpad>/interests/EEG.png")

Palette (matches the site: sky / ink, one steel blue, carmine rationed):
    INK     #10243A   lines, text, dark marks
    STEEL   #1D5A88   the main data colour
    SKY     #8FB8D8   secondary data, fills
    PALE    #D8E5F0   background fills, regions
    MUTED   #6B7F93   de-emphasised marks, grids
    CARMINE #9B2242   AT MOST ONE highlighted element per figure
    SAND    #C9A45C   optional second accent, use rarely (a 2nd class)

Colormaps:  fs.CMAP_SEQ (pale -> steel -> ink),  fs.CMAP_DIV (steel <- white -> carmine)
"""
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import LinearSegmentedColormap

INK = "#10243A"
STEEL = "#1D5A88"
SKY = "#8FB8D8"
PALE = "#D8E5F0"
MUTED = "#6B7F93"
CARMINE = "#9B2242"
SAND = "#C9A45C"
WHITE = "#FFFFFF"

CMAP_SEQ = LinearSegmentedColormap.from_list(
    "hahn_seq", ["#F4F8FB", PALE, SKY, STEEL, INK])
CMAP_DIV = LinearSegmentedColormap.from_list(
    "hahn_div", [INK, STEEL, SKY, "#F7F7F7", "#E3A9B6", CARMINE, "#5E1027"])

W_IN, H_IN, DPI = 4.8, 3.6, 250          # -> 1200 x 900 px


def setup():
    plt.rcParams.update({
        "figure.facecolor": WHITE,
        "axes.facecolor": WHITE,
        "savefig.facecolor": WHITE,
        "font.family": "DejaVu Sans",
        "font.size": 8.5,
        "axes.labelsize": 8.5,
        "axes.titlesize": 9,
        "xtick.labelsize": 7.5,
        "ytick.labelsize": 7.5,
        "axes.edgecolor": MUTED,
        "axes.labelcolor": INK,
        "xtick.color": MUTED,
        "ytick.color": MUTED,
        "text.color": INK,
        "axes.linewidth": 0.7,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "lines.linewidth": 1.4,
        "axes.prop_cycle": matplotlib.cycler(color=[STEEL, SKY, INK, SAND, MUTED]),
        "legend.frameon": False,
        "legend.fontsize": 7.5,
        "image.cmap": "hahn_seq",
    })
    try:
        matplotlib.colormaps.register(CMAP_SEQ)
        matplotlib.colormaps.register(CMAP_DIV)
    except ValueError:
        pass


def figure(nrows=1, ncols=1, **kw):
    fig, ax = plt.subplots(nrows, ncols, figsize=(W_IN, H_IN), dpi=DPI, **kw)
    return fig, ax


def clean(ax):
    """Remove all axes decoration (for pictures that are not charts)."""
    ax.set_xticks([]); ax.set_yticks([])
    for s in ax.spines.values():
        s.set_visible(False)


CREDIT = "Generated by AI"


def credit(fig):
    """Rule for every generated image in the Homepage folder: mark it as generated,
    bottom-right, inside the image, readable on light or full-bleed backgrounds."""
    fig.text(0.988, 0.014, CREDIT, ha="right", va="bottom", fontsize=8.5, color=INK, alpha=0.78,
             zorder=100, bbox=dict(boxstyle="round,pad=0.25", fc="white", ec="none", alpha=0.78))


def save(fig, path):
    credit(fig)                     # always: see credit()
    fig.savefig(path, dpi=DPI, bbox_inches=None, pad_inches=0)
    plt.close(fig)
